### PR TITLE
Update project dependencies

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates the build dependencies to the latest version (as of August 19th, 2017):

- Gradle wrapper `4.1`
- Android Gradle plugin `2.3.3`
- Build tools `25.0.3`

The update to `play-services-safetynet` version `10.2.4` required increasing `compileSdkVersion` to `14`.

<sub><sup>Please NO GitHub rebase/squash merges. The changes are broken up into meaningful, independent commits, and my branch should already be up-to-date with the latest target branch. If not, or if you'd like me to combine some or all of the commits, please let me know, and I will make the necessary updates as soon as possible. Thank you!</sup></sub>

### CODE REVIEW

**Comment by friederbluemle** [comment]
Updated to the latest versions.

**Comment by friederbluemle** [comment]
Updated again to the latest versions. @scottyab Could you take a look please?

**Comment by friederbluemle** [comment]
@scottyab Updated this one as well (Gradle wrapper `4.1` is out now). Please note the comment about no GitHub squash merges in the PR description :)

**Comment by scottyab** [comment]
Excellent mate thanks. I might of missed the no GitHub squash so thanks for flagging that.

**Comment by friederbluemle** [comment]
No worries, thanks for merging @scottyab, and of course, thanks for this project! 👍 :)

**Pull request merged**
