### PR TITLE
Fix view for atv

### PR DESCRIPTION
**Pull request by jalong4**
We would like to use your tool for ATV.  Android TV apps such as Disney+ use SafetyNet filters and this tool would be helpful to OEMs to help them troubleshoot failures.

### CODE REVIEW

**Comment by scottyab** [comment]
I believe this is resolved now. LMK if not. Thanks

**Comment by jalong4** [comment]
It's not resolved because the manifest locks the orientation in portrait and does not include a LEANBACK_LAUNCHER so it won't show up in the play store on Android TV and you can't read the UX since it shows up in the shape of a phone on the TV.

**Comment by scottyab** [comment]
@jalong4 ah sorry I missed that.

**Comment by scottyab** [comment]
Thanks, I'll include in the next release

**Comment by jalong4** [comment]
awesome.  I just pulled your latest and tested.  It works great!  thx.
test4
test3
test2
test

**Comment by jalong4** [comment]
By the way, if you can provide me with the exact RGB values for the background color of your SafetyNet icon, I can push a change where the Android TV banner file matches exactly.  I tried to match it as best I could but you can see it doesn't match exactly.

**Comment by scottyab** [comment]
The app's primary colour is #8BC34A. I just used the color picker on the web icon and looks like it's slightly different #8BBF51 https://c.hlp.sc/wbukWm5A

**Pull request merged**
